xenon-ssh:
  image: nlesc/xenon-ssh
# For ssh gateway tests
xenon-ssh2:
  image: nlesc/xenon-ssh
  links:
    - xenon-ssh
xenon-ftp:
  image: nlesc/xenon-ftp
xenon-torque:
  image: nlesc/xenon-torque
  cap_add:
    - SYS_RESOURCE
xenon-slurm:
  image: nlesc/xenon-slurm
xenon-gridengine:
  image: nlesc/xenon-gridengine
xenon-gridengine-exec1:
  image: nlesc/xenon-gridengine-exec
  volumes_from:
    - xenon-gridengine
  links:
    - xenon-gridengine
xenon-test:
  image: nlesc/xenon-test
  volumes:
    - ../../..:/code
  environment:
    - MYUID
  command: ./gradlew -Pxenon.test.properties=src/integrationTest/docker/xenon.test.properties.docker --stacktrace --project-cache-dir /home/xenon/gradle-cache integrationTest
  links:
    - xenon-ssh
    - xenon-ssh2
    - xenon-ftp
    - xenon-torque
    - xenon-slurm
    - xenon-gridengine
    - xenon-gridengine-exec1
