version: '3'
services:
  # next line is value of property 'JobCompHost' in etc/slurm.conf (hostname of MySQL container)
  mysql:
    hostname: mysql
    image: mysql:5.5
    environment:
    # next line is value of property 'JobCompPass' in etc/slurm.conf (user password of MySQL container)
    - MYSQL_ROOT_PASSWORD=xenon-slurm-pw
    healthcheck:
      test: mysqladmin -pxenon-slurm-pw ping || exit 1
      interval: 1s
      timeout: 1s
      retries: 1
  slurm:
    image: nlesc/xenon-slurm:15.08
    depends_on:
    - mysql
    ports:
    - 22 # ssh
    - 6817 # slurm controller
